labels: []
body:
  - type: markdown
    attributes:
      value: |
        When asking for help troubleshooting something, please remember
        to share as much context about what you're trying to do,
        specifically what configuration you tried, what happened and how it
        didn't match up to what you expected!
  - type: dropdown
    id: os
    attributes:
      label: What Windows version are you running on?
      options:
        - Windows 10
        - Windows 11
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: OnlyTerm version
      description: |
        Please run `onlyterm -V` and include its output here.
      placeholder: "ex: 20240812-120000-abcd1234"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Ask your question!
      description: |
        Please remember to share as much context as you can, as that makes it
        quicker and easier for others to understand and respond
      placeholder: Tell us what is on your mind!
    validations:
      required: true
