[package]
name = "config"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
env_logger.workspace = true
tempfile.workspace = true

[features]
distro-defaults = []

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
colorgrad.workspace = true
dirs-next.workspace = true
dunce.workspace = true
enum-display-derive.workspace = true
hostname.workspace = true
ktav.workspace = true
lazy_static.workspace = true
log.workspace = true
notify.workspace = true
ordered-float = { workspace=true, features = ["serde"] }
portable-pty = { workspace=true, features = ["serde_support"]}
promise.workspace = true
serde = {workspace=true, features = ["rc", "derive"]}
serde_json.workspace = true
shlex.workspace = true
smol.workspace = true
termwiz = { workspace=true, features=["use_serde"] }
toml.workspace = true
umask.workspace = true
onlyterm-bidi.workspace = true
onlyterm-config-derive.workspace = true
onlyterm-color-schemes-data.workspace = true
onlyterm-dynamic.workspace = true
onlyterm-input-types.workspace = true
onlyterm-term = { workspace = true, features=["use_serde"] }

[target."cfg(windows)".dependencies]
winapi = { workspace=true, features = ["winuser"]}
winreg.workspace = true
