//! Tests for UP-40: precision pointing devices (trackpads, Magic Mouse,
//! high-resolution mice) report a continuous scroll *magnitude* for a
//! single wheel gesture (`MouseButton::WheelUp(n)` / `WheelDown(n)` / etc,
//! where `n` is the number of "ticks" represented by that single gesture)
//! rather than always reporting a single discrete tick the way a
//! mechanical wheel does.
//!
//! Prior to this fix, `TerminalState::mouse_wheel` completely discarded
//! that magnitude and always emitted exactly one wheel report/key-press,
//! regardless of how large a swipe the user made. That made scrolling
//! inside mouse-tracking TUIs (vim, tmux, less, etc) feel sluggish with
//! such devices: <https://github.com/wezterm/wezterm/issues/7645> and the
//! related reports #817, #6371, #5234.
use super::*;
use k9::assert_equal as assert_eq;
use std::sync::{Condvar, Mutex};
use std::time::Duration;

/// A `Write` implementation that appends everything written to it into a
/// shared buffer and notifies a `Condvar` so that a test on another thread
/// can synchronize with it. This is needed because `TerminalState` always
/// dispatches its writer through an internal background thread
/// (`ThreadedWriter`), so a plain `Vec<u8>` capture isn't observable
/// synchronously from the test thread.
#[derive(Clone)]
struct SyncWriter {
    state: Arc<(Mutex<Vec<u8>>, Condvar)>,
}

impl SyncWriter {
    fn new() -> Self {
        Self {
            state: Arc::new((Mutex::new(Vec::new()), Condvar::new())),
        }
    }

    /// Blocks (with a generous timeout to avoid hanging the test suite
    /// if something is broken) until at least `len` bytes have been
    /// observed, then returns a copy of everything written so far.
    fn wait_for_len(&self, len: usize) -> Vec<u8> {
        let (lock, cvar) = &*self.state;
        let guard = lock.lock().unwrap();
        let (guard, timed_out) = cvar
            .wait_timeout_while(guard, Duration::from_secs(5), |buf| buf.len() < len)
            .unwrap();
        assert!(
            !timed_out.timed_out(),
            "timed out waiting for {} bytes, only got {:?}",
            len,
            guard
        );
        guard.clone()
    }
}

impl std::io::Write for SyncWriter {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        let (lock, cvar) = &*self.state;
        let mut data = lock.lock().unwrap();
        data.extend_from_slice(buf);
        cvar.notify_all();
        Ok(buf.len())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

fn wheel_event(button: MouseButton) -> MouseEvent {
    MouseEvent {
        kind: MouseEventKind::Press,
        x: 0,
        y: 0,
        x_pixel_offset: 0,
        y_pixel_offset: 0,
        button,
        modifiers: KeyModifiers::NONE,
    }
}

/// With SGR mouse reporting enabled, a single `WheelUp(5)` event (as
/// generated by a fast trackpad swipe) must be forwarded to the
/// application as 5 discrete "CSI < 64 ; x ; y M" wheel-up reports, not
/// just one.
#[test]
fn wheel_up_sgr_forwards_full_magnitude() {
    let writer = SyncWriter::new();
    let mut term = TestTerm::new_with_writer(24, 80, 0, Box::new(writer.clone()));

    // Turn on mouse tracking (?1000) and SGR encoding (?1006), as a
    // well-behaved TUI like vim/tmux would on startup.
    term.set_mode("?1000", true);
    term.set_mode("?1006", true);

    term.mouse_event(wheel_event(MouseButton::WheelUp(5)))
        .unwrap();

    let expected = "\x1b[<64;1;1M".repeat(5);
    let got = writer.wait_for_len(expected.len());
    assert_eq!(
        String::from_utf8_lossy(&got),
        expected,
        "WheelUp(5) should produce 5 discrete SGR wheel-up reports"
    );
}

/// Same as above, but for WheelDown, and using the X10/UTF8 encoding
/// (the default once mouse tracking is enabled without also requesting
/// SGR encoding).
#[test]
fn wheel_down_x10_forwards_full_magnitude() {
    let writer = SyncWriter::new();
    let mut term = TestTerm::new_with_writer(24, 80, 0, Box::new(writer.clone()));

    // Turn on basic X10-style mouse tracking only.
    term.set_mode("?1000", true);

    term.mouse_event(wheel_event(MouseButton::WheelDown(3)))
        .unwrap();

    // X10 encoding: ESC [ M <32+button> <32+x+1> <32+y+1>, with button
    // code 65 for wheel-down => 32+65 = 97, and x=y=0 => 32+0+1 = 33.
    let mut expected = Vec::new();
    for _ in 0..3 {
        expected.extend_from_slice(&[0x1b, b'[', b'M', 97, 33, 33]);
    }

    let got = writer.wait_for_len(expected.len());
    assert_eq!(
        got, expected,
        "WheelDown(3) should produce 3 discrete X10 wheel-down reports"
    );
}

/// When mouse tracking has *not* been requested by the application and
/// the alt screen is active, wheel events are translated into cursor-key
/// presses (xterm's alternateScroll equivalent). The number of cursor-key
/// presses must scale with both the configured
/// `alternate_buffer_wheel_scroll_speed` (default: 3) *and* the actual
/// scroll magnitude of the gesture.
#[test]
fn wheel_down_alt_screen_fallback_scales_with_magnitude() {
    let writer = SyncWriter::new();
    let mut term = TestTerm::new_with_writer(24, 80, 0, Box::new(writer.clone()));

    // Activate the alternate screen, but do *not* enable any mouse
    // tracking mode.
    term.set_mode("?1049", true);
    assert!(term.is_alt_screen_active());

    term.mouse_event(wheel_event(MouseButton::WheelDown(3)))
        .unwrap();

    // Default alternate_buffer_wheel_scroll_speed() is 3, so a WheelDown(3)
    // gesture should produce 3 * 3 = 9 DownArrow ("\x1b[B") presses.
    let expected = "\x1b[B".repeat(9);
    let got = writer.wait_for_len(expected.len());
    assert_eq!(
        String::from_utf8_lossy(&got),
        expected,
        "WheelDown(3) in the alt screen fallback path should send \
         3 * alternate_buffer_wheel_scroll_speed() == 9 down-arrow presses"
    );
}
